### ISSUE TITLE
The performance of the FSRNet networks is poor in low-resolution image.

### ISSUE THREAD

**Issue by hwpengTristin** [liang23333/FSR-Tensorflow#1]
Input low-resolution images (128x128x3)
![2](https://user-images.githubusercontent.com/29362830/62408251-42dff080-b5f8-11e9-925d-b8e6fa552a45.png)

Output super-resolution images (128x128x3)
![1](https://user-images.githubusercontent.com/29362830/62408254-48d5d180-b5f8-11e9-9d41-3c493132cb2b.png)

The results seems unsatisfactory. What's the problem?

**Comment by liang23333** [comment]
Hi, i think the problem is that the dataset i use is different from you.  You can compare the face in your dataset and the face i provided [face](https://user-images.githubusercontent.com/29362830/62408254-48d5d180-b5f8-11e9-9d41-3c493132cb2b.png), the alignment and the ratio of face are different. A good method to handle it is that you can retrain on yoru dataset.

**Comment by liang23333** [comment]
> Input low-resolution images (128x128x3)
> ![2](https://user-images.githubusercontent.com/29362830/62408251-42dff080-b5f8-11e9-925d-b8e6fa552a45.png)
> 
> Output super-resolution images (128x128x3)
> ![1](https://user-images.githubusercontent.com/29362830/62408254-48d5d180-b5f8-11e9-9d41-3c493132cb2b.png)
> 
> The results seems unsatisfactory. What's the problem?

Hi, i think the problem is that the dataset i use is different from you.  You can compare the face in your dataset and the face i provided [face](https://user-images.githubusercontent.com/29362830/62408254-48d5d180-b5f8-11e9-9d41-3c493132cb2b.png), the alignment and the ratio of face are different. A good method to handle it is that you can retrain on yoru dataset.

**Comment by hwpengTristin** [comment]
Thank you very much.
